version: "3.8"
services:
  frontend:
    build: ./containers/frontend
    ports:
      - "3000:80"
    volumes:
      - replay_data:/app/data

  mitm:
    build: ./containers/mitm
    ports:
      - "4000:80"
    volumes:
      - replay_data:/app/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - mitm

volumes:
  replay_data: