version: "3.8"
services:
  frontend:
    build: ./containers/frontend
    ports:
      - "3000:80"
    volumes:
      - replay_data:/app/data

  mitm:
    build: ./containers/mitm
    ports:
      - "4000:8080"
    volumes:
      - replay_data:/app/data

volumes:
  replay_data: